# Scientific computing with python
The most common libraries for scientific computing with python are [numpy](https://numpy.org/doc/stable/) and [scipy](https://docs.scipy.org/doc/scipy/reference/).

We can only give a short introduction here. However, the official documentation and guides are fairly well explained.

In [2]:
import numpy as np
import scipy

In [32]:
vec = np.array([1.,2.,3.])
vec

array([1., 2., 3.])

In [3]:
int_vec = np.array([1.,2.,3.,], dtype=np.int64)
int_vec

array([1, 2, 3], dtype=int64)

In [4]:
mat = np.array([[1., 2., 3.],
                [4., 5., 6.]])
mat

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
vec.shape, vec.ndim, mat.shape, mat.ndim

((3,), 1, (2, 3), 2)

In [6]:
np.random.randn(2,3), np.ones((3,3)), np.zeros((3,2)), np.eye(2)

(array([[-0.08293982, -1.76640985, -0.66131766],
        [-0.21718537, -0.97275055,  1.39161773]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0.],
        [0., 0.],
        [0., 0.]]),
 array([[1., 0.],
        [0., 1.]]))

## Broadcasting

In [15]:
#also see broadcasting bookmark in numpy
mat, vec

(array([[1., 2., 3.],
        [4., 5., 6.]]),
 array([1., 2., 3.]))

In [16]:
mat.T.shape, vec.shape

((3, 2), (3,))

In [17]:
#vec is automatically transposed to fit the shape of mat possible
#all ops are element-wise
mat - vec, mat / vec, mat * vec,

(array([[0., 0., 0.],
        [3., 3., 3.]]),
 array([[1. , 1. , 1. ],
        [4. , 2.5, 2. ]]),
 array([[ 1.,  4.,  9.],
        [ 4., 10., 18.]]))

## Operations

In [18]:
#normal matrix mutiplication
mat @ vec # python 3.

array([14., 32.])

In [19]:
#same as @
np.matmul(mat, vec)

array([14., 32.])

In [20]:
#slicing always excludes the last index
#1. start including 1st pos, end excluding the 3rd number
#2. start from 0th, end before the last
#3. start from second last(including), end at end(including cuz here : specified)
vec[0], vec[1:3], vec[:-1], vec[-2:]

(1.0, array([2., 3.]), array([1., 2.]), array([2., 3.]))

In [21]:
#3. take all rows but only 1st col, 4. take 2nd row and all cols
#will not preserve shape - use keepdims=true for that
mat[1][2], mat[1,2], mat[:,0], mat[1,:]

(6.0, 6.0, array([1., 4.]), array([4., 5., 6.]))

In [48]:
print(vec)
print(vec.shape)
#list so shape is (3,0)

A = vec[None,:]
#adds a dim at front, same as transpose
print(A)
print(A.shape)

B = vec[:, None]
#adds a dim at back, like a matrix
print(B)
print(B.shape)

[1. 2. 3.]
(3,)
[[1. 2. 3.]]
(1, 3)
[[1.]
 [2.]
 [3.]]
(3, 1)


In [49]:
#inner and dot product are same thing for a finite-dim space(a.T @ b)
#see outer product (np.outer) for (a @ b.T)
#below is basically vec.T @ vec
vec[None,:] @ vec[:, None], np.inner(vec, vec), np.dot(vec,vec)

(array([[14.]]), 14.0, 14.0)

In [22]:
mat.T, mat.T.shape

(array([[1., 4.],
        [2., 5.],
        [3., 6.]]),
 (3, 2))

In [23]:
np.mean(mat), np.mean(mat, axis=0), np.mean(mat, axis=1) # also sum, max, min
#to preserve shape - use keepdims=true

(3.5, array([2.5, 3.5, 4.5]), array([2., 5.]))

In [27]:
#reshape needs to be assigned like A=A.reshape(...)
A = np.arange(10).reshape(2,5)
A, A.shape

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 (2, 5))

In [29]:
vec = np.random.rand(10000)

In [54]:
%%timeit -r 10 -n 100
#Measure execution time of small code snippets
#-r how many times to repeat the timer (default 5)
#-n how many times to execute ‘statement’
#needs to be the first line of execution
for i in range(vec.shape[0]):
    vec[i] ** 2

1.14 µs ± 196 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [55]:
#use vector ops, they fast
%%timeit -r 10 -n 100
vec ** 2

548 ns ± 87.3 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)


## Sparse matrices with scipy

In [61]:
from scipy.sparse import coo_matrix
#A sparse matrix in COOrdinate format.

In [62]:
#row and col define the coordinates of the data
row  = np.array([0, 3, 1, 0])
col  = np.array([0, 3, 1, 2])
data = np.array([4, 5, 7, 9])

B = coo_matrix((data, (row, col)), shape=(4, 4))

In [63]:
print(B)

  (0, 0)	4
  (3, 3)	5
  (1, 1)	7
  (0, 2)	9


In [64]:
B.todense()

matrix([[4, 0, 9, 0],
        [0, 7, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 5]])

In [76]:
C = B.todense()
C[-1,-1]

5

In [69]:
# B[0,0] can't access sparse matrices directly
print(B.getrow(0)), print(B.getcol(1)),  print(B.getcol(-1))

  (0, 2)	9
  (0, 0)	4
  (1, 0)	7
  (3, 0)	5


(None, None, None)

In [67]:
#if value is present, it will display it, otherwise will display 0
B.getrow(0)[0,0], B.getrow(0)[0,2], B.getrow(0)[0,3], B.getcol(-1)[-1,0]

(4, 9, 0, 5)

In [83]:
#first arg [[1., 2, 3, 4, 5], [6, 5, 8, 9, 10]] is data to set
#2nd arg:
#k = 0 the main diagonal
#k > 0 the kth upper diagonal
#k < 0 the kth lower diagonal
#last two args tell the shape of the matrix
mtx = scipy.sparse.spdiags([[1., 2, 3, 4, 5], [6, 5, 8, 9, 10], [11,12,13,14,15]], [0, -1, 2], 5, 5)
mtx.todense()

matrix([[ 1.,  0., 13.,  0.,  0.],
        [ 6.,  2.,  0., 14.,  0.],
        [ 0.,  5.,  3.,  0., 15.],
        [ 0.,  0.,  8.,  4.,  0.],
        [ 0.,  0.,  0.,  9.,  5.]])

In [84]:
rhs = np.array([1, 2, 3, 4, 5], dtype=np.float32)

In [72]:
#solving a linear system Ax=B
import scipy.sparse.linalg
scipy.sparse.linalg.spsolve(mtx, rhs)

C:\Users\lenovo1\.conda\envs\shapeanalysis\lib\site-packages\scipy\sparse\linalg\_dsolve\linsolve.py:214: SparseEfficiencyWarning: spsolve requires A be CSC or CSR matrix format
  warn('spsolve requires A be CSC or CSR matrix format',


array([ 1.        , -2.        ,  4.33333333, -7.66666667, 14.8       ])

In [86]:
#k-number of eigenvalues and eigenvectors desired. k must be smaller than N-1
#which finds the LM-largest magnitude(see docs for more)
#return - w: k eigenvalues
#k eigenvectors. v[:, i] is the eigenvector corresponding to the eigenvalue w[i].
scipy.sparse.linalg.eigs(mtx, k=3, which='LM')

(array([16.11758132 +0.j       , -3.04909959+10.8536174j,
        -3.04909959-10.8536174j]),
 array([[-0.45953717+0.j        ,  0.41664028-0.33136012j,
          0.41664028+0.33136012j],
        [-0.54516992+0.j        , -0.57141505-0.20233191j,
         -0.57141505+0.20233191j],
        [-0.53439158+0.j        ,  0.14687984+0.4510588j ,
          0.14687984-0.4510588j ],
        [-0.35280412+0.j        ,  0.18438021-0.22801183j,
          0.18438021+0.22801183j],
        [-0.28560503+0.j        , -0.19513568-0.00817749j,
         -0.19513568+0.00817749j]]))

In [3]:
#useful for above situation
K = np.array([1,8,2,4,5,5,6,10])
#prints indices of sorted array(asc), last 5 items, items from 5th element to last(see slicing in numpy)
np.sort(K), np.argsort(K), np.argsort(K)[-5:], np.argsort(K)[5:]

(array([ 1,  2,  4,  5,  5,  6,  8, 10]),
 array([0, 2, 3, 4, 5, 6, 1, 7], dtype=int64),
 array([4, 5, 6, 1, 7], dtype=int64),
 array([6, 1, 7], dtype=int64))